module.exports = {
    usernameInput: '',
    passwordInput: '',
    neobux: 'http://www.neobux.com',
    mainPageLoginButton: '/html/body/div[1]/div[1]/table/tbody/tr[2]/td[2]/table/tbody/tr/td[1]/a[4]',
    loginPageImage: '//*[@id="Kf0"]/tbody/tr[1]/td[1]/table/tbody/tr[4]/td[2]/table/tbody/tr/td[2]/img',
    loginPageUsernameField: '//*[@id="Kf1"]',
    loginPagePasswordField: '//*[@id="Kf2"]',
    loginPageCodeField: '//*[@id="Kf3"]',
    loginPageLoginButton: '//*[@id="botao_login"]',
    userPageLoginButton: '//*[@id="ubar_w1"]/tbody/tr/td[3]/a',
    userAdvertisementsPage: '/html/body/div[1]/div[1]/table/tbody/tr[3]/td/table/tbody/tr/td[3]/a',
    activeAdColor: 'rgba(255, 255, 255, 1)',
    advertiseCloseButton: '//*[@id="o1"]/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/a',
    userAdPrizeButton: '//*[@id="ap_hct"]',
    adPrizeNextButton: '//*[@id="nxt_bt_a"]',
    adPrizeCloseButton: '//*[@id="prm0"]/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/a/span',
    userAdPrizeZero: '//*[@id="t_0c"]',
    username: '//*[@id="t_conta"]',
    profileStatisticsButton: '//*[@id="menu_w"]/table/tbody/tr/td/div[4]/a[3]',
    profileStatistics: '//*[@id="ch_cliques"]',
    profileProfit: '//*[@id="t_saldo"]/span',
    advertisementsPage: '/html/body/div[1]/div[1]/table/tbody/tr[3]/td/table/tbody/tr/td[1]/a'
};